
markdown: rdiscount
highlighter: pygments

permalink: /:title

title: xurisui's blog
url: http://xurisui.github.io
feed: /atom.xml  
author_info: <a href="http://xurisui.github.io/">xurisui</a>
